version: "3.7"
services:
  pipeline_service:
    image: "ml_pipeline_a:latest"
    depends_on:
      - postgresdb
    links:
       - postgresdb:db
  postgresdb:
    image: "postgres:13"
    container_name: postgresdb
    # command: 
      # - /media/command.sh
    env_file:
      - ./db_init/dbinit.env
    volumes:
      - ./db/:/var/lib/postgresql/data/pgdat
      - ./db_init/init-user-db.sh:/docker-entrypoint-initdb.d/init-user-db.sh
      - ./db_init/auto-mpg.data:/media/data/auto-mpg.data
    expose:
      - "5432"
    restart: always